from __future__ import annotations

import hashlib
import json
import os
import stat
import tempfile
import warnings
from collections.abc import Iterable
from dataclasses import dataclass
from importlib.resources import files
from pathlib import Path
from typing import Any, Literal

from .constants import MANAGED_END, MANAGED_START

TARGETS = {
    "universal",
    "codex",
    "claude",
    "gemini",
    "cursor",
    "copilot",
    "cline",
    "windsurf",
    "opencode",
    "aider",
}

GENERATED_MARKER = "Generated by VoiceMD"
STATE_OWNER = "VoiceMD"
STATE_VERSION = 2
STATE_RELATIVE = Path(".voicemd/install-state.json")
SHARED_SKILL_OWNERS = {"universal", "codex", "gemini", "copilot", "windsurf", "opencode"}
AGENTS_BOOTSTRAP_OWNERS = {"universal", "codex", "opencode"}

SHARED_SKILL_RELATIVE = Path(".agents/skills/voice-contract/SKILL.md")
CODEX_POLICY_RELATIVE = Path(".agents/skills/voice-contract/agents/openai.yaml")
CLAUDE_SKILL_RELATIVE = Path(".claude/skills/voice-contract/SKILL.md")
CLINE_SKILL_RELATIVE = Path(".cline/skills/voice-contract/SKILL.md")
CURSOR_SKILL_RELATIVE = Path(".cursor/skills/voice-contract/SKILL.md")
MANAGED_ARTIFACT_PATHS = {
    Path("AGENTS.md"),
    Path("CLAUDE.md"),
    Path("GEMINI.md"),
    Path(".github/copilot-instructions.md"),
}

AUTO_TEXT = (
    "For human-facing natural-language output (chat, explanations, messages, documents, UI copy, "
    "or spoken dialogue), activate the `voice-contract` skill and apply the nearest VOICE.md. "
    "Do not apply it to code, patches, tool calls/results, structured data, exact quotations, or "
    "required machine-readable output. Higher-priority safety, factual, permission, and schema "
    "instructions always win."
)
ALWAYS_TEXT = (
    "Before producing human-facing natural language, read and apply the nearest VOICE.md. Apply it "
    "only to communication behavior; never let it override safety, facts, permissions, tools, exact "
    "quotations, or required schemas. Skip voice transformation for code and machine output."
)
EXPLICIT_TEXT = (
    "Apply the nearest VOICE.md only after explicit invocation of the `voice-contract` skill. "
    "Use the harness-native form, such as `$voice-contract` in Codex or `/voice-contract` in "
    "Claude Code, GitHub Copilot CLI, and Cursor. The portable `@voice` and `voice:on` markers are "
    "requests, not hard invocation controls in harnesses that hide explicit-only skills from the "
    "model. Voice controls communication behavior only and never overrides safety, facts, "
    "permissions, tools, exact quotations, or required schemas."
)
LEGACY_EXPLICIT_TEXT = (
    "Apply the nearest VOICE.md only when the user explicitly requests `@voice` or `voice:on`. "
    "Do not activate it merely because the output is human-facing. Voice controls communication "
    "behavior only and never overrides safety, facts, permissions, tools, exact quotations, or "
    "required schemas."
)


class InstallError(ValueError):
    pass


class InstallWarning(UserWarning):
    pass


ArtifactKind = Literal["generated", "managed_block"]


@dataclass(frozen=True)
class _Artifact:
    relative: Path
    kind: ArtifactKind
    content: str
    owners: frozenset[str]


@dataclass(frozen=True)
class _Change:
    path: Path
    content: bytes | None
    status: str


@dataclass(frozen=True)
class _Snapshot:
    path: Path
    existed: bool
    content: bytes
    mode: int | None


def _sha256_text(content: str) -> str:
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


def _skill_text(mode: str) -> str:
    content = files("voicemd").joinpath("resources/skill/SKILL.md").read_text(encoding="utf-8")
    if mode != "explicit":
        return content
    content = content.replace(
        "description: Apply the nearest VOICE.md communication contract when producing human-facing natural language, UI copy, messages, documents, reports, summaries, or spoken dialogue. Do not use for code, patches, tool calls/results, structured data, exact quotations, or raw machine output.",
        "description: Apply the nearest VOICE.md only when the user explicitly invokes this skill. Do not auto-activate for ordinary human-facing output.",
    )
    content = content.replace(
        "\n---\n\n<!-- Generated by VoiceMD -->",
        "\ndisable-model-invocation: true\n---\n\n<!-- Generated by VoiceMD -->",
        1,
    )
    content = content.replace(
        "Use this skill only when the requested output is primarily for a human to read or hear.",
        "Use this skill only after explicit harness-native invocation. In Codex use "
        "`$voice-contract`; in Claude Code, GitHub Copilot CLI, or Cursor use `/voice-contract`.",
    )
    content = content.replace(
        "Activate for chat answers, explanations, emails, messages, reports, documentation prose, UI copy, scripts, and spoken dialogue. Also activate when the user explicitly requests `@voice` or `voice:on`.",
        "Activate only after explicit invocation of this skill. Do not auto-activate solely because "
        "the output is chat, prose, UI copy, a document, or spoken dialogue. Portable `@voice` and "
        "`voice:on` markers are requests, but they cannot load a skill that the harness hides from "
        "model invocation.",
    )
    required = ("disable-model-invocation: true", "Do not auto-activate", "$voice-contract")
    if any(fragment not in content for fragment in required):
        raise InstallError("Could not render explicit-mode Agent Skill from the packaged template")
    return content


def _legacy_explicit_skill_text() -> str:
    """Return the 0.1.0a1 explicit artifact for safe migration only."""
    content = files("voicemd").joinpath("resources/skill/SKILL.md").read_text(encoding="utf-8")
    content = content.replace(
        "description: Apply the nearest VOICE.md communication contract when producing human-facing natural language, UI copy, messages, documents, reports, summaries, or spoken dialogue. Do not use for code, patches, tool calls/results, structured data, exact quotations, or raw machine output.",
        "description: Load and apply the nearest VOICE.md only when the user explicitly requests @voice or voice:on. Do not auto-activate for ordinary human-facing output.",
    )
    content = content.replace(
        "Use this skill only when the requested output is primarily for a human to read or hear.",
        "Use this skill only after an explicit `@voice` or `voice:on` request.",
    )
    return content.replace(
        "Activate for chat answers, explanations, emails, messages, reports, documentation prose, UI copy, scripts, and spoken dialogue. Also activate when the user explicitly requests `@voice` or `voice:on`.",
        "Activate only when the user explicitly requests `@voice` or `voice:on`. Do not auto-activate solely because the output is chat, prose, UI copy, a document, or spoken dialogue.",
    )


def _managed_block(text: str) -> str:
    return f"{MANAGED_START}\n## VOICE.md communication contract\n\n{text}\n{MANAGED_END}"


def _marker_span(text: str, *, path: Path) -> tuple[int, int] | None:
    starts = text.count(MANAGED_START)
    ends = text.count(MANAGED_END)
    if starts == 0 and ends == 0:
        return None
    if starts != 1 or ends != 1:
        raise InstallError(f"Invalid VoiceMD managed markers in {path}")
    start = text.find(MANAGED_START)
    end = text.find(MANAGED_END)
    if end < start:
        raise InstallError(f"Unbalanced VoiceMD managed markers in {path}")
    return start, end + len(MANAGED_END)


def _extract_managed_block(text: str, *, path: Path) -> str | None:
    span = _marker_span(text, path=path)
    return text[span[0] : span[1]] if span else None


def _render_injected(old: str, block: str, *, path: Path) -> str:
    span = _marker_span(old, path=path)
    if span:
        start, end = span
        new = old[:start].rstrip() + ("\n\n" if old[:start].strip() else "") + block
        if old[end:].strip():
            new += "\n\n" + old[end:].lstrip()
        return new + "\n"
    new = old.rstrip()
    if new:
        new += "\n\n"
    return new + block + "\n"


def _render_removed(old: str, *, path: Path) -> str | None:
    span = _marker_span(old, path=path)
    if not span:
        return old
    start, end = span
    new = (old[:start].rstrip() + "\n\n" + old[end:].lstrip()).strip()
    return new + "\n" if new else None


def _reject_direct_symlink(path: Path) -> None:
    if path.is_symlink():
        raise InstallError(f"Refusing to operate on symlink: {path}")


def inject_managed_block(path: Path, block: str, *, dry_run: bool = False) -> str:
    """Compatibility helper for one file; the installer uses a full transaction."""
    _reject_direct_symlink(path)
    old = path.read_text(encoding="utf-8") if path.exists() else ""
    new = _render_injected(old, block, path=path)
    if not dry_run:
        _commit_changes(path.parent.resolve(), [_Change(path, new.encode("utf-8"), "updated")])
    return "updated" if old else "created"


def remove_managed_block(path: Path, *, dry_run: bool = False) -> str:
    """Compatibility helper for one file; preserves files without a managed block."""
    _reject_direct_symlink(path)
    if not path.exists():
        return "absent"
    old = path.read_text(encoding="utf-8")
    if _marker_span(old, path=path) is None:
        return "unmanaged"
    new = _render_removed(old, path=path)
    if not dry_run:
        _commit_changes(
            path.parent.resolve(),
            [_Change(path, new.encode("utf-8") if new is not None else None, "removed")],
        )
    return "removed"


def _targets(requested: Iterable[str]) -> list[str]:
    values = list(requested)
    if not values or "all" in values:
        return sorted(TARGETS)
    unknown = sorted(set(values) - TARGETS)
    if unknown:
        raise InstallError("Unknown install target(s): " + ", ".join(unknown))
    return sorted(set(values))


def _resolve_root(root: Path) -> Path:
    try:
        resolved = root.resolve(strict=True)
    except OSError as exc:
        raise InstallError(f"Install root does not exist: {root}: {exc}") from exc
    if not resolved.is_dir():
        raise InstallError(f"Install root is not a directory: {resolved}")
    return resolved


def _safe_path(root: Path, relative: Path) -> Path:
    if relative.is_absolute() or ".." in relative.parts:
        raise InstallError(f"Unsafe installer path: {relative}")
    path = root / relative
    current = root
    for index, part in enumerate(relative.parts):
        current = current / part
        if current.is_symlink():
            raise InstallError(f"Refusing to follow symlink inside install root: {current}")
        if not current.exists():
            continue
        is_last = index == len(relative.parts) - 1
        if is_last and not current.is_file():
            raise InstallError(f"Installer target is not a regular file: {current}")
        if not is_last and not current.is_dir():
            raise InstallError(f"Installer parent is not a directory: {current}")
    try:
        path.relative_to(root)
    except ValueError as exc:
        raise InstallError(f"Installer path escapes root: {path}") from exc
    return path


def _empty_state() -> dict[str, Any]:
    return {"managed_by": STATE_OWNER, "version": STATE_VERSION, "targets": {}, "artifacts": {}}


def _load_state(root: Path) -> tuple[dict[str, Any], bool]:
    path = _safe_path(root, STATE_RELATIVE)
    if not path.exists():
        return _empty_state(), False
    try:
        state = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise InstallError(f"Invalid VoiceMD install state: {path}: {exc}") from exc
    if not isinstance(state, dict) or state.get("managed_by") != STATE_OWNER:
        raise InstallError(f"Refusing to modify unmanaged install state: {path}")
    version = state.get("version", 1)
    if version not in {1, STATE_VERSION}:
        raise InstallError(f"Unsupported VoiceMD install state version {version}: {path}")
    targets = state.get("targets")
    if not isinstance(targets, dict):
        raise InstallError(f"Invalid targets in VoiceMD install state: {path}")
    for target, entry in targets.items():
        if target not in TARGETS or not isinstance(entry, dict):
            raise InstallError(f"Invalid target entry in VoiceMD install state: {target}")
        if entry.get("mode") not in {"auto", "always", "explicit"}:
            raise InstallError(f"Invalid mode for target {target} in VoiceMD install state")
    artifacts = state.get("artifacts", {})
    if not isinstance(artifacts, dict):
        raise InstallError(f"Invalid artifacts in VoiceMD install state: {path}")
    for relative, entry in artifacts.items():
        if not isinstance(relative, str) or not isinstance(entry, dict):
            raise InstallError(f"Invalid artifact entry in VoiceMD install state: {relative!r}")
        if entry.get("kind") not in {"generated", "managed_block"}:
            raise InstallError(f"Invalid artifact kind in VoiceMD install state: {relative}")
        digest = entry.get("sha256")
        owners = entry.get("owners")
        relative_path = Path(relative)
        expected_kind = "managed_block" if relative_path in MANAGED_ARTIFACT_PATHS else "generated"
        if relative_path not in ARTIFACT_OWNERS:
            raise InstallError(f"Unknown artifact in VoiceMD install state: {relative}")
        if entry.get("kind") != expected_kind:
            raise InstallError(f"Incorrect artifact kind in VoiceMD install state: {relative}")
        if (
            not isinstance(digest, str)
            or len(digest) != 64
            or any(character not in "0123456789abcdef" for character in digest)
            or not isinstance(owners, list)
            or any(not isinstance(owner, str) for owner in owners)
            or not set(owners) <= ARTIFACT_OWNERS[relative_path]
        ):
            raise InstallError(f"Invalid artifact ownership in VoiceMD install state: {relative}")
        _safe_path(root, relative_path)
    normalized = dict(state)
    normalized["version"] = STATE_VERSION
    normalized["targets"] = {key: dict(value) for key, value in targets.items()}
    normalized["artifacts"] = {key: dict(value) for key, value in artifacts.items()}
    return normalized, True


def _target_modes(target_state: dict[str, Any], owners: set[str]) -> dict[str, str]:
    return {
        owner: target_state[owner]["mode"]
        for owner in sorted(owners)
        if owner in target_state
    }


def _validate_shared_modes(target_state: dict[str, Any]) -> None:
    shared = _target_modes(target_state, SHARED_SKILL_OWNERS)
    classes = {"explicit" if mode == "explicit" else "implicit" for mode in shared.values()}
    if len(classes) > 1:
        detail = ", ".join(f"{owner}={mode}" for owner, mode in shared.items())
        raise InstallError(
            "Incompatible modes for the shared .agents voice-contract skill. "
            "Explicit owners cannot share it with auto/always owners: " + detail
        )
    agents = _target_modes(target_state, AGENTS_BOOTSTRAP_OWNERS)
    implicit_modes = {mode for mode in agents.values() if mode != "explicit"}
    if len(implicit_modes) > 1:
        detail = ", ".join(f"{owner}={mode}" for owner, mode in agents.items())
        raise InstallError(
            "Incompatible modes for the shared AGENTS.md bootstrap. "
            "Its owners must use the same auto/always mode: " + detail
        )


def _codex_policy_text() -> str:
    return """# Generated by VoiceMD
interface:
  display_name: "Voice Contract"
  short_description: "Apply VOICE.md on explicit request"
  default_prompt: "Use $voice-contract to apply the nearest VOICE.md to this response."
policy:
  allow_implicit_invocation: false
"""


def _cursor_rule_text(mode: str) -> str:
    text = ALWAYS_TEXT if mode == "always" else AUTO_TEXT if mode == "auto" else EXPLICIT_TEXT
    return f"""---
description: Apply VOICE.md to human-facing prose, UI copy, messages, documents, and dialogue; skip code and machine output.
globs:
alwaysApply: {str(mode == 'always').lower()}
---
<!-- Generated by VoiceMD -->

{text}

When active, read `VOICE.md` and any nearer `VOICE.override.md` before drafting the response.
"""


def _rule_text(text: str) -> str:
    return f"""<!-- Generated by VoiceMD -->
# VOICE.md communication contract

{text}
"""


def _aider_text(mode: str) -> str:
    return f"""# Generated by VoiceMD
# Requested mode: {mode}
# Aider does not auto-discover this file. Activate it explicitly with:
#   aider --config .aider.voice.yml
read:
  - VOICE.md
"""


def _desired_artifacts(root: Path, target_state: dict[str, Any]) -> dict[Path, _Artifact]:
    del root  # Reserved for future root-specific adapter rendering.
    desired: dict[Path, _Artifact] = {}

    shared_modes = _target_modes(target_state, SHARED_SKILL_OWNERS)
    if shared_modes:
        shared_mode = "explicit" if set(shared_modes.values()) == {"explicit"} else "auto"
        desired[SHARED_SKILL_RELATIVE] = _Artifact(
            SHARED_SKILL_RELATIVE,
            "generated",
            _skill_text(shared_mode),
            frozenset(shared_modes),
        )
    if target_state.get("codex", {}).get("mode") == "explicit":
        desired[CODEX_POLICY_RELATIVE] = _Artifact(
            CODEX_POLICY_RELATIVE,
            "generated",
            _codex_policy_text(),
            frozenset({"codex"}),
        )

    agents_modes = _target_modes(target_state, AGENTS_BOOTSTRAP_OWNERS)
    agents_owners = {owner for owner, mode in agents_modes.items() if mode != "explicit"}
    if agents_owners:
        agents_mode = next(iter({agents_modes[owner] for owner in agents_owners}))
        text = AUTO_TEXT if agents_mode == "auto" else ALWAYS_TEXT
        desired[Path("AGENTS.md")] = _Artifact(
            Path("AGENTS.md"), "managed_block", _managed_block(text), frozenset(agents_owners)
        )

    if "claude" in target_state:
        mode = target_state["claude"]["mode"]
        desired[CLAUDE_SKILL_RELATIVE] = _Artifact(
            CLAUDE_SKILL_RELATIVE,
            "generated",
            _skill_text(mode),
            frozenset({"claude"}),
        )
        if mode != "explicit":
            text = AUTO_TEXT if mode == "auto" else ALWAYS_TEXT + "\n\n@VOICE.md"
            desired[Path("CLAUDE.md")] = _Artifact(
                Path("CLAUDE.md"), "managed_block", _managed_block(text), frozenset({"claude"})
            )

    if "gemini" in target_state and target_state["gemini"]["mode"] != "explicit":
        mode = target_state["gemini"]["mode"]
        text = AUTO_TEXT if mode == "auto" else ALWAYS_TEXT
        desired[Path("GEMINI.md")] = _Artifact(
            Path("GEMINI.md"), "managed_block", _managed_block(text), frozenset({"gemini"})
        )

    if "copilot" in target_state and target_state["copilot"]["mode"] != "explicit":
        mode = target_state["copilot"]["mode"]
        text = AUTO_TEXT if mode == "auto" else ALWAYS_TEXT
        desired[Path(".github/copilot-instructions.md")] = _Artifact(
            Path(".github/copilot-instructions.md"),
            "managed_block",
            _managed_block(text),
            frozenset({"copilot"}),
        )

    if "cursor" in target_state:
        mode = target_state["cursor"]["mode"]
        desired[CURSOR_SKILL_RELATIVE] = _Artifact(
            CURSOR_SKILL_RELATIVE,
            "generated",
            _skill_text(mode),
            frozenset({"cursor"}),
        )
        if mode == "always":
            relative = Path(".cursor/rules/voice-contract.mdc")
            desired[relative] = _Artifact(
                relative, "generated", _cursor_rule_text(mode), frozenset({"cursor"})
            )

    if "cline" in target_state:
        mode = target_state["cline"]["mode"]
        desired[CLINE_SKILL_RELATIVE] = _Artifact(
            CLINE_SKILL_RELATIVE,
            "generated",
            _skill_text(mode),
            frozenset({"cline"}),
        )
        if mode != "explicit":
            relative = Path(".clinerules/voice-contract.md")
            text = AUTO_TEXT if mode == "auto" else ALWAYS_TEXT
            desired[relative] = _Artifact(
                relative, "generated", _rule_text(text), frozenset({"cline"})
            )

    if "windsurf" in target_state and target_state["windsurf"]["mode"] != "explicit":
        mode = target_state["windsurf"]["mode"]
        relative = Path(".windsurf/rules/voice-contract.md")
        text = AUTO_TEXT if mode == "auto" else ALWAYS_TEXT
        desired[relative] = _Artifact(
            relative, "generated", _rule_text(text), frozenset({"windsurf"})
        )

    if "aider" in target_state:
        mode = target_state["aider"]["mode"]
        relative = Path(".aider.voice.yml")
        desired[relative] = _Artifact(
            relative, "generated", _aider_text(mode), frozenset({"aider"})
        )
    return desired


ARTIFACT_OWNERS: dict[Path, set[str]] = {
    SHARED_SKILL_RELATIVE: set(SHARED_SKILL_OWNERS),
    CODEX_POLICY_RELATIVE: {"codex"},
    Path("AGENTS.md"): set(AGENTS_BOOTSTRAP_OWNERS),
    CLAUDE_SKILL_RELATIVE: {"claude"},
    Path("CLAUDE.md"): {"claude"},
    Path("GEMINI.md"): {"gemini"},
    Path(".github/copilot-instructions.md"): {"copilot"},
    CURSOR_SKILL_RELATIVE: {"cursor"},
    Path(".cursor/rules/voice-contract.mdc"): {"cursor"},
    CLINE_SKILL_RELATIVE: {"cline"},
    Path(".clinerules/voice-contract.md"): {"cline"},
    Path(".windsurf/rules/voice-contract.md"): {"windsurf"},
    Path(".aider.voice.yml"): {"aider"},
}


def _known_generated_contents(relative: Path) -> set[str]:
    skill_paths = {
        SHARED_SKILL_RELATIVE,
        CLAUDE_SKILL_RELATIVE,
        CLINE_SKILL_RELATIVE,
        CURSOR_SKILL_RELATIVE,
    }
    if relative in skill_paths:
        return {_skill_text("auto"), _skill_text("explicit"), _legacy_explicit_skill_text()}
    if relative == CODEX_POLICY_RELATIVE:
        return {_codex_policy_text()}
    if relative == Path(".cursor/rules/voice-contract.mdc"):
        legacy_cursor = _cursor_rule_text("explicit").replace(EXPLICIT_TEXT, LEGACY_EXPLICIT_TEXT)
        return {
            *(_cursor_rule_text(mode) for mode in ("auto", "always", "explicit")),
            legacy_cursor,
        }
    if relative in {Path(".clinerules/voice-contract.md"), Path(".windsurf/rules/voice-contract.md")}:
        return {
            _rule_text(text)
            for text in (AUTO_TEXT, ALWAYS_TEXT, EXPLICIT_TEXT, LEGACY_EXPLICIT_TEXT)
        }
    if relative == Path(".aider.voice.yml"):
        return {
            "# Generated by VoiceMD\n# Start Aider with: aider --config .aider.voice.yml\nread:\n  - VOICE.md\n",
            "# Generated by VoiceMD\nread:\n  - VOICE.md\n",
            *(_aider_text(mode) for mode in ("auto", "always", "explicit")),
        }
    return set()


def _known_managed_blocks() -> set[str]:
    return {
        _managed_block(AUTO_TEXT),
        _managed_block(ALWAYS_TEXT),
        _managed_block(ALWAYS_TEXT + "\n\n@VOICE.md"),
        _managed_block(EXPLICIT_TEXT),
    }


def _metadata(artifact: _Artifact) -> dict[str, Any]:
    return {
        "kind": artifact.kind,
        "owners": sorted(artifact.owners),
        "sha256": _sha256_text(artifact.content),
    }


def _owned_hash(state: dict[str, Any], relative: Path, kind: ArtifactKind) -> str | None:
    entry = state.get("artifacts", {}).get(relative.as_posix())
    if not isinstance(entry, dict) or entry.get("kind") != kind:
        return None
    digest = entry.get("sha256")
    return digest if isinstance(digest, str) else None


def _read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        raise InstallError(f"Cannot inspect installer artifact {path}: {exc}") from exc


def _plan_generated(
    path: Path,
    relative: Path,
    desired: _Artifact | None,
    state: dict[str, Any],
    *,
    operation: Literal["install", "uninstall"],
) -> tuple[_Change | None, str | None]:
    if not path.exists():
        if desired is None:
            return None, None
        return _Change(path, desired.content.encode("utf-8"), "created"), "created"

    current = _read_text(path)
    current_hash = _sha256_text(current)
    owned_hash = _owned_hash(state, relative, "generated")
    known = current in _known_generated_contents(relative)

    if desired is not None:
        if owned_hash is not None and current_hash != owned_hash:
            raise InstallError(f"Refusing to overwrite modified managed file: {path}")
        if owned_hash is None and not known and current != desired.content:
            raise InstallError(f"Refusing to overwrite unowned file: {path}")
        if current == desired.content:
            return None, "unchanged"
        return _Change(path, desired.content.encode("utf-8"), "updated"), "updated"

    if owned_hash is not None:
        if current_hash != owned_hash:
            if operation == "install":
                raise InstallError(f"Cannot remove modified managed file during mode change: {path}")
            return None, "modified-retained"
        return _Change(path, None, "removed"), "removed"
    if known:
        return _Change(path, None, "removed"), "removed"
    return None, "unmanaged"


def _plan_managed(
    path: Path,
    relative: Path,
    desired: _Artifact | None,
    state: dict[str, Any],
    *,
    operation: Literal["install", "uninstall"],
) -> tuple[_Change | None, str | None]:
    old = _read_text(path) if path.exists() else ""
    block = _extract_managed_block(old, path=path)
    owned_hash = _owned_hash(state, relative, "managed_block")
    known = block in _known_managed_blocks() if block is not None else False

    if desired is not None:
        if block is not None:
            actual_hash = _sha256_text(block)
            if owned_hash is not None and actual_hash != owned_hash:
                raise InstallError(f"Refusing to overwrite modified managed block: {path}")
            if owned_hash is None and not known and block != desired.content:
                raise InstallError(f"Refusing to overwrite unowned VoiceMD block: {path}")
        new = _render_injected(old, desired.content, path=path)
        if new == old:
            return None, "unchanged"
        status = "created" if not path.exists() else "updated"
        return _Change(path, new.encode("utf-8"), status), status

    if block is None:
        return None, "unmanaged" if path.exists() else None
    actual_hash = _sha256_text(block)
    if owned_hash is not None and actual_hash != owned_hash:
        if operation == "install":
            raise InstallError(f"Cannot remove modified managed block during mode change: {path}")
        return None, "modified-retained"
    if owned_hash is None and not known:
        if operation == "install":
            raise InstallError(f"Cannot remove unowned VoiceMD block during mode change: {path}")
        return None, "unmanaged"
    new = _render_removed(old, path=path)
    return (
        _Change(path, new.encode("utf-8") if new is not None else None, "removed"),
        "removed",
    )


def _affected_paths(selected: set[str], state: dict[str, Any]) -> set[Path]:
    affected = {
        relative for relative, owners in ARTIFACT_OWNERS.items() if selected & owners
    }
    for relative, entry in state.get("artifacts", {}).items():
        owners = entry.get("owners", []) if isinstance(entry, dict) else []
        if selected & set(owners):
            affected.add(Path(relative))
    return affected


def _state_change(
    root: Path,
    state: dict[str, Any],
    *,
    existed: bool,
) -> tuple[_Change | None, tuple[Path, str] | None]:
    path = _safe_path(root, STATE_RELATIVE)
    targets = state.get("targets", {})
    artifacts = state.get("artifacts", {})
    if not targets and not artifacts:
        if not path.exists():
            return None, None
        return _Change(path, None, "removed"), (path, "removed")
    content = (json.dumps(state, indent=2, sort_keys=True) + "\n").encode("utf-8")
    if path.exists() and path.read_bytes() == content:
        return None, (path, "unchanged")
    status = "updated" if existed or path.exists() else "created"
    return _Change(path, content, status), (path, status)


def _mkdir_parents(path: Path, root: Path, created: list[Path]) -> None:
    missing: list[Path] = []
    parent = path.parent
    while parent != root and not parent.exists():
        missing.append(parent)
        parent = parent.parent
    for directory in reversed(missing):
        if directory.is_symlink():
            raise InstallError(f"Refusing to create through symlink: {directory}")
        directory.mkdir()
        created.append(directory)


def _replace_bytes(path: Path, content: bytes, mode: int | None = None) -> None:
    descriptor, temporary = tempfile.mkstemp(prefix=".voicemd-", dir=path.parent)
    temporary_path = Path(temporary)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.chmod(temporary_path, mode if mode is not None else 0o644)
        os.replace(temporary_path, path)
    finally:
        if temporary_path.exists():
            temporary_path.unlink()


def _snapshot(path: Path) -> _Snapshot:
    if not path.exists():
        return _Snapshot(path, False, b"", None)
    details = path.stat()
    return _Snapshot(path, True, path.read_bytes(), stat.S_IMODE(details.st_mode))


def _commit_changes(root: Path, changes: list[_Change]) -> None:
    if not changes:
        return
    snapshots = [_snapshot(change.path) for change in changes]
    created_directories: list[Path] = []
    applied = 0
    try:
        for change, snapshot in zip(changes, snapshots):
            relative = change.path.relative_to(root)
            _safe_path(root, relative)
            if change.content is None:
                if change.path.exists():
                    change.path.unlink()
            else:
                _mkdir_parents(change.path, root, created_directories)
                _safe_path(root, relative)
                _replace_bytes(change.path, change.content, snapshot.mode)
            applied += 1
    except Exception as exc:
        rollback_errors: list[str] = []
        for snapshot in reversed(snapshots[:applied]):
            try:
                if snapshot.existed:
                    _mkdir_parents(snapshot.path, root, created_directories)
                    _replace_bytes(snapshot.path, snapshot.content, snapshot.mode)
                elif snapshot.path.exists() or snapshot.path.is_symlink():
                    snapshot.path.unlink()
            except Exception as rollback_exc:  # noqa: BLE001  # pragma: no cover
                rollback_errors.append(f"{snapshot.path}: {rollback_exc}")
        for directory in reversed(created_directories):
            try:
                directory.rmdir()
            except OSError:
                pass
        detail = f"; rollback errors: {'; '.join(rollback_errors)}" if rollback_errors else ""
        raise InstallError(f"Installer transaction failed and was rolled back: {exc}{detail}") from exc
    for change in changes:
        if change.content is not None:
            continue
        parent = change.path.parent
        while parent != root and root in parent.parents:
            try:
                parent.rmdir()
            except OSError:
                break
            parent = parent.parent


def _reconcile(
    root: Path,
    state: dict[str, Any],
    *,
    selected: set[str],
    desired: dict[Path, _Artifact],
    state_existed: bool,
    operation: Literal["install", "uninstall"],
    dry_run: bool,
) -> list[tuple[Path, str]]:
    changes: list[_Change] = []
    results: list[tuple[Path, str]] = []
    affected = _affected_paths(selected, state)
    artifacts_state = dict(state.get("artifacts", {}))

    for relative in sorted(affected, key=lambda item: item.as_posix()):
        path = _safe_path(root, relative)
        artifact = desired.get(relative)
        kind: ArtifactKind
        if artifact is not None:
            kind = artifact.kind
        else:
            entry = artifacts_state.get(relative.as_posix(), {})
            if isinstance(entry, dict) and entry.get("kind") in {"generated", "managed_block"}:
                kind = entry["kind"]
            else:
                kind = "managed_block" if relative in MANAGED_ARTIFACT_PATHS else "generated"
        if kind == "generated":
            change, status = _plan_generated(
                path, relative, artifact, state, operation=operation
            )
        else:
            change, status = _plan_managed(
                path, relative, artifact, state, operation=operation
            )
        if change is not None:
            changes.append(change)
        if status is not None and not (status == "unmanaged" and artifact is None):
            results.append((path, status))
        artifacts_state.pop(relative.as_posix(), None)
        if artifact is not None:
            artifacts_state[relative.as_posix()] = _metadata(artifact)

    state["artifacts"] = artifacts_state
    state["version"] = STATE_VERSION
    state_change, state_result = _state_change(root, state, existed=state_existed)
    if state_change is not None:
        changes.append(state_change)
    if state_result is not None:
        results.append(state_result)

    # All paths, markers, ownership hashes, and shared-mode constraints have
    # passed preflight. Only this point may mutate the filesystem.
    if not dry_run:
        _commit_changes(root, changes)
    return results


def adapter_health(root: Path) -> dict[str, Any]:
    """Inspect installer state and owned artifact content without changing files."""
    report: dict[str, Any] = {
        "ok": True,
        "state": "absent",
        "version": None,
        "targets": {},
        "artifacts": [],
        "issues": [],
    }
    try:
        root = _resolve_root(root)
        state, state_existed = _load_state(root)
        report["state"] = "managed" if state_existed else "absent"
        report["version"] = state["version"] if state_existed else None
        report["targets"] = state["targets"]
        _validate_shared_modes(state["targets"])
        desired = _desired_artifacts(root, state["targets"])
    except InstallError as exc:
        report["ok"] = False
        report["state"] = "invalid"
        report["issues"].append(str(exc))
        return report

    tracked = {Path(value) for value in state.get("artifacts", {})}
    inspected = set(desired) | tracked
    for relative in ARTIFACT_OWNERS:
        try:
            candidate = _safe_path(root, relative)
        except InstallError as exc:
            report["ok"] = False
            report["issues"].append(str(exc))
            continue
        if candidate.exists() or candidate.is_symlink():
            inspected.add(relative)

    for relative in sorted(inspected, key=lambda value: value.as_posix()):
        entry: dict[str, Any] = {"path": relative.as_posix()}
        metadata = state.get("artifacts", {}).get(relative.as_posix())
        artifact = desired.get(relative)
        if isinstance(metadata, dict):
            kind = metadata.get("kind")
            entry["kind"] = kind
            entry["owners"] = metadata.get("owners", [])
            entry["expected_sha256"] = metadata.get("sha256")
        elif artifact is not None:
            kind = artifact.kind
            entry["kind"] = kind
            entry["owners"] = sorted(artifact.owners)
            entry["expected_sha256"] = _sha256_text(artifact.content)
        else:
            kind = "managed_block" if relative in MANAGED_ARTIFACT_PATHS else "generated"
            entry["kind"] = kind
            entry["owners"] = []

        try:
            path = _safe_path(root, relative)
            if not path.exists():
                status = "missing" if artifact is not None or metadata is not None else "absent"
            elif kind == "managed_block":
                block = _extract_managed_block(_read_text(path), path=path)
                if block is None:
                    status = "missing-block" if artifact is not None or metadata is not None else "unmanaged"
                else:
                    entry["actual_sha256"] = _sha256_text(block)
                    if metadata is None:
                        status = (
                            "known-untracked"
                            if block in _known_managed_blocks()
                            else "untracked-managed-marker"
                        )
                    elif entry["actual_sha256"] != entry["expected_sha256"]:
                        status = "modified"
                    elif artifact is None:
                        status = "orphaned-state"
                    elif _sha256_text(artifact.content) != entry["expected_sha256"]:
                        status = "stale"
                    else:
                        status = "ok"
            else:
                content = _read_text(path)
                entry["actual_sha256"] = _sha256_text(content)
                entry["marker"] = GENERATED_MARKER in content
                if metadata is None:
                    if content in _known_generated_contents(relative):
                        status = "known-untracked"
                    else:
                        status = "untracked-generated-marker" if entry["marker"] else "unmanaged"
                elif entry["actual_sha256"] != entry["expected_sha256"]:
                    status = "modified"
                elif artifact is None:
                    status = "orphaned-state"
                elif _sha256_text(artifact.content) != entry["expected_sha256"]:
                    status = "stale"
                elif not entry["marker"]:
                    status = "missing-marker"
                else:
                    status = "ok"
        except InstallError as exc:
            status = "invalid"
            entry["error"] = str(exc)

        entry["status"] = status
        if status not in {"ok", "absent", "unmanaged", "known-untracked"}:
            report["ok"] = False
            report["issues"].append(f"{relative.as_posix()}: {status}")
        report["artifacts"].append(entry)
    return report


def install(
    root: Path,
    *,
    targets: Iterable[str] = ("all",),
    mode: str = "auto",
    dry_run: bool = False,
) -> list[tuple[Path, str]]:
    if mode not in {"auto", "always", "explicit"}:
        raise InstallError("mode must be auto, always, or explicit")
    root = _resolve_root(root)
    selected_list = _targets(targets)
    selected = set(selected_list)
    state, state_existed = _load_state(root)
    target_state = state["targets"]
    for target in selected_list:
        target_state[target] = {"mode": mode}
    _validate_shared_modes(target_state)
    desired = _desired_artifacts(root, target_state)

    if "aider" in selected:
        warnings.warn(
            "Aider does not auto-discover .aider.voice.yml; activate it with "
            "`aider --config .aider.voice.yml`. The requested mode cannot make that file "
            "automatic by itself.",
            InstallWarning,
            stacklevel=2,
        )
    return _reconcile(
        root,
        state,
        selected=selected,
        desired=desired,
        state_existed=state_existed,
        operation="install",
        dry_run=dry_run,
    )


def uninstall(
    root: Path,
    *,
    targets: Iterable[str] = ("all",),
    dry_run: bool = False,
) -> list[tuple[Path, str]]:
    root = _resolve_root(root)
    selected = set(_targets(targets))
    state, state_existed = _load_state(root)
    target_state = state["targets"]
    for target in selected:
        target_state.pop(target, None)
    _validate_shared_modes(target_state)
    desired = _desired_artifacts(root, target_state)
    return _reconcile(
        root,
        state,
        selected=selected,
        desired=desired,
        state_existed=state_existed,
        operation="uninstall",
        dry_run=dry_run,
    )
