from __future__ import annotations

import json
from importlib.resources import files
from pathlib import Path
from typing import Any, Iterable

from .constants import MANAGED_END, MANAGED_START

TARGETS = {
    "universal",
    "codex",
    "claude",
    "gemini",
    "cursor",
    "copilot",
    "cline",
    "windsurf",
    "opencode",
    "aider",
}

GENERATED_MARKER = "Generated by VoiceMD"
STATE_OWNER = "VoiceMD"
STATE_VERSION = 1
STATE_RELATIVE = Path(".voicemd/install-state.json")
SHARED_SKILL_OWNERS = {"universal", "codex", "gemini", "copilot", "windsurf", "opencode"}
AGENTS_BOOTSTRAP_OWNERS = {"universal", "codex", "opencode"}

AUTO_TEXT = (
    "For human-facing natural-language output (chat, explanations, messages, documents, UI copy, "
    "or spoken dialogue), activate the `voice-contract` skill and apply the nearest VOICE.md. "
    "Do not apply it to code, patches, tool calls/results, structured data, exact quotations, or "
    "required machine-readable output. Higher-priority safety, factual, permission, and schema "
    "instructions always win."
)
ALWAYS_TEXT = (
    "Before producing human-facing natural language, read and apply the nearest VOICE.md. Apply it "
    "only to communication behavior; never let it override safety, facts, permissions, tools, exact "
    "quotations, or required schemas. Skip voice transformation for code and machine output."
)
EXPLICIT_TEXT = (
    "Apply the nearest VOICE.md only when the user explicitly requests `@voice` or `voice:on`. "
    "Do not activate it merely because the output is human-facing. Voice controls communication "
    "behavior only and never overrides safety, facts, permissions, tools, exact quotations, or "
    "required schemas."
)


class InstallError(ValueError):
    pass


def _skill_text(mode: str) -> str:
    content = files("voicemd").joinpath("resources/skill/SKILL.md").read_text(encoding="utf-8")
    if mode != "explicit":
        return content
    content = content.replace(
        "description: Apply the nearest VOICE.md communication contract when producing human-facing natural language, UI copy, messages, documents, reports, summaries, or spoken dialogue. Do not use for code, patches, tool calls/results, structured data, exact quotations, or raw machine output.",
        "description: Load and apply the nearest VOICE.md only when the user explicitly requests @voice or voice:on. Do not auto-activate for ordinary human-facing output.",
    )
    content = content.replace(
        "Use this skill only when the requested output is primarily for a human to read or hear.",
        "Use this skill only after an explicit `@voice` or `voice:on` request.",
    )
    content = content.replace(
        "Activate for chat answers, explanations, emails, messages, reports, documentation prose, UI copy, scripts, and spoken dialogue. Also activate when the user explicitly requests `@voice` or `voice:on`.",
        "Activate only when the user explicitly requests `@voice` or `voice:on`. Do not auto-activate solely because the output is chat, prose, UI copy, a document, or spoken dialogue.",
    )
    if "Do not auto-activate" not in content:
        raise InstallError("Could not render explicit-mode Agent Skill from the packaged template")
    return content


def _managed_block(text: str) -> str:
    return f"{MANAGED_START}\n## VOICE.md communication contract\n\n{text}\n{MANAGED_END}"


def inject_managed_block(path: Path, block: str, *, dry_run: bool = False) -> str:
    old = path.read_text(encoding="utf-8") if path.exists() else ""
    start = old.find(MANAGED_START)
    end = old.find(MANAGED_END)
    if start != -1 and end != -1 and end >= start:
        end += len(MANAGED_END)
        new = old[:start].rstrip() + ("\n\n" if old[:start].strip() else "") + block
        if old[end:].strip():
            new += "\n\n" + old[end:].lstrip()
        new += "\n"
    elif start != -1 or end != -1:
        raise InstallError(f"Unbalanced VoiceMD managed markers in {path}")
    else:
        new = old.rstrip()
        if new:
            new += "\n\n"
        new += block + "\n"
    if not dry_run:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(new, encoding="utf-8")
    return "updated" if old else "created"


def remove_managed_block(path: Path, *, dry_run: bool = False) -> str:
    if not path.exists():
        return "absent"
    old = path.read_text(encoding="utf-8")
    start = old.find(MANAGED_START)
    end = old.find(MANAGED_END)
    if start == -1 and end == -1:
        return "unmanaged"
    if start == -1 or end == -1 or end < start:
        raise InstallError(f"Unbalanced VoiceMD managed markers in {path}")
    end += len(MANAGED_END)
    new = (old[:start].rstrip() + "\n\n" + old[end:].lstrip()).strip()
    if not dry_run:
        if new:
            path.write_text(new + "\n", encoding="utf-8")
        else:
            path.unlink()
    return "removed"


def _write_generated(path: Path, content: str, *, dry_run: bool = False) -> str:
    if GENERATED_MARKER not in content:
        raise InstallError(f"Generated content is missing its ownership marker: {path}")
    if path.exists():
        old = path.read_text(encoding="utf-8")
        if GENERATED_MARKER not in old and old != content:
            raise InstallError(f"Refusing to overwrite unmanaged file: {path}")
        status = "updated"
    else:
        status = "created"
    if not dry_run:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return status


def _copy_skill(path: Path, *, mode: str, dry_run: bool = False) -> str:
    return _write_generated(path, _skill_text(mode), dry_run=dry_run)


def _remove_generated_file(path: Path, *, root: Path, dry_run: bool = False) -> str:
    if not path.exists():
        return "absent"
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        raise InstallError(f"Cannot inspect managed file {path}: {exc}") from exc
    if GENERATED_MARKER not in text:
        return "unmanaged"
    if not dry_run:
        path.unlink()
        parent = path.parent
        while parent != root and root in parent.parents:
            try:
                parent.rmdir()
            except OSError:
                break
            parent = parent.parent
    return "removed"


def _targets(requested: Iterable[str]) -> list[str]:
    values = list(requested)
    if not values or "all" in values:
        return sorted(TARGETS)
    unknown = sorted(set(values) - TARGETS)
    if unknown:
        raise InstallError("Unknown install target(s): " + ", ".join(unknown))
    return sorted(set(values))


def _empty_state() -> dict[str, Any]:
    return {"managed_by": STATE_OWNER, "version": STATE_VERSION, "targets": {}}


def _load_state(root: Path) -> tuple[dict[str, Any], bool]:
    path = root / STATE_RELATIVE
    if not path.exists():
        return _empty_state(), False
    try:
        state = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise InstallError(f"Invalid VoiceMD install state: {path}: {exc}") from exc
    if not isinstance(state, dict) or state.get("managed_by") != STATE_OWNER:
        raise InstallError(f"Refusing to modify unmanaged install state: {path}")
    targets = state.get("targets")
    if not isinstance(targets, dict):
        raise InstallError(f"Invalid targets in VoiceMD install state: {path}")
    state["version"] = STATE_VERSION
    return state, True


def _write_state(
    root: Path,
    state: dict[str, Any],
    *,
    existed: bool,
    dry_run: bool,
) -> tuple[Path, str] | None:
    path = root / STATE_RELATIVE
    targets = state.get("targets", {})
    if not targets:
        if not existed and not path.exists():
            return None
        if not dry_run and path.exists():
            path.unlink()
            try:
                path.parent.rmdir()
            except OSError:
                pass
        return path, "removed"

    content = json.dumps(state, indent=2, sort_keys=True) + "\n"
    if not dry_run:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return path, "updated" if existed else "created"


def _should_remove_shared(
    *,
    selected: set[str],
    remaining: set[str],
    owners: set[str],
    state_existed: bool,
) -> bool:
    if state_existed:
        return not bool(remaining & owners)
    # Legacy/untracked install: remove only when every possible owner is being
    # uninstalled. This deliberately prefers leaving a harmless managed file
    # over breaking another harness that may share it.
    return owners <= selected


def install(
    root: Path,
    *,
    targets: Iterable[str] = ("all",),
    mode: str = "auto",
    dry_run: bool = False,
) -> list[tuple[Path, str]]:
    if mode not in {"auto", "always", "explicit"}:
        raise InstallError("mode must be auto, always, or explicit")
    root = root.resolve()
    selected = _targets(targets)
    results: list[tuple[Path, str]] = []
    if mode == "auto":
        text = AUTO_TEXT
    elif mode == "always":
        text = ALWAYS_TEXT
    else:
        text = EXPLICIT_TEXT
    state, state_existed = _load_state(root)

    # Canonical Agent Skills location shared by Codex, Gemini CLI, GitHub Copilot,
    # OpenCode, and Windsurf. Create once to avoid duplicate skill names.
    if set(selected) & SHARED_SKILL_OWNERS:
        path = root / ".agents/skills/voice-contract/SKILL.md"
        results.append((path, _copy_skill(path, mode=mode, dry_run=dry_run)))

    if "claude" in selected:
        path = root / ".claude/skills/voice-contract/SKILL.md"
        results.append((path, _copy_skill(path, mode=mode, dry_run=dry_run)))
    if "cline" in selected:
        path = root / ".cline/skills/voice-contract/SKILL.md"
        results.append((path, _copy_skill(path, mode=mode, dry_run=dry_run)))

    if mode != "explicit":
        if set(selected) & AGENTS_BOOTSTRAP_OWNERS:
            path = root / "AGENTS.md"
            results.append((path, inject_managed_block(path, _managed_block(text), dry_run=dry_run)))
        if "claude" in selected:
            path = root / "CLAUDE.md"
            claude_text = text + ("\n\n@VOICE.md" if mode == "always" else "")
            results.append(
                (path, inject_managed_block(path, _managed_block(claude_text), dry_run=dry_run))
            )
        if "gemini" in selected:
            path = root / "GEMINI.md"
            results.append((path, inject_managed_block(path, _managed_block(text), dry_run=dry_run)))
        if "copilot" in selected:
            path = root / ".github/copilot-instructions.md"
            results.append((path, inject_managed_block(path, _managed_block(text), dry_run=dry_run)))

    if "cursor" in selected:
        cursor = f"""---
description: Apply VOICE.md to human-facing prose, UI copy, messages, documents, and dialogue; skip code and machine output.
globs:
alwaysApply: {str(mode == 'always').lower()}
---
<!-- Generated by VoiceMD -->

{text}

When active, read `VOICE.md` and any nearer `VOICE.override.md` before drafting the response.
"""
        path = root / ".cursor/rules/voice-contract.mdc"
        results.append((path, _write_generated(path, cursor, dry_run=dry_run)))

    if "cline" in selected:
        cline = f"""<!-- Generated by VoiceMD -->
# VOICE.md communication contract

{text}
"""
        path = root / ".clinerules/voice-contract.md"
        results.append((path, _write_generated(path, cline, dry_run=dry_run)))

    if "windsurf" in selected:
        windsurf = f"""<!-- Generated by VoiceMD -->
# VOICE.md communication contract

{text}
"""
        path = root / ".windsurf/rules/voice-contract.md"
        results.append((path, _write_generated(path, windsurf, dry_run=dry_run)))

    if "aider" in selected:
        aider = """# Generated by VoiceMD
# Start Aider with: aider --config .aider.voice.yml
read:
  - VOICE.md
"""
        path = root / ".aider.voice.yml"
        results.append((path, _write_generated(path, aider, dry_run=dry_run)))

    target_state = state["targets"]
    for target in selected:
        target_state[target] = {"mode": mode}
    state_result = _write_state(
        root, state, existed=state_existed, dry_run=dry_run
    )
    if state_result:
        results.append(state_result)
    return results


def uninstall(
    root: Path,
    *,
    targets: Iterable[str] = ("all",),
    dry_run: bool = False,
) -> list[tuple[Path, str]]:
    root = root.resolve()
    selected = set(_targets(targets))
    results: list[tuple[Path, str]] = []
    state, state_existed = _load_state(root)
    target_state = state["targets"]
    remaining = set(target_state) - selected

    shared_skill = root / ".agents/skills/voice-contract/SKILL.md"
    if selected & SHARED_SKILL_OWNERS:
        if _should_remove_shared(
            selected=selected,
            remaining=remaining,
            owners=SHARED_SKILL_OWNERS,
            state_existed=state_existed,
        ):
            status = _remove_generated_file(shared_skill, root=root, dry_run=dry_run)
        else:
            status = "retained-shared"
        if status != "absent":
            results.append((shared_skill, status))

    for owner, relative in (
        ("claude", ".claude/skills/voice-contract/SKILL.md"),
        ("cline", ".cline/skills/voice-contract/SKILL.md"),
    ):
        if owner not in selected:
            continue
        path = root / relative
        status = _remove_generated_file(path, root=root, dry_run=dry_run)
        if status != "absent":
            results.append((path, status))

    managed_groups = [
        (AGENTS_BOOTSTRAP_OWNERS, "AGENTS.md"),
        ({"claude"}, "CLAUDE.md"),
        ({"gemini"}, "GEMINI.md"),
        ({"copilot"}, ".github/copilot-instructions.md"),
    ]
    for owners, relative in managed_groups:
        if not (selected & owners):
            continue
        if len(owners) > 1 and not _should_remove_shared(
            selected=selected,
            remaining=remaining,
            owners=owners,
            state_existed=state_existed,
        ):
            path = root / relative
            if path.exists():
                results.append((path, "retained-shared"))
            continue
        path = root / relative
        status = remove_managed_block(path, dry_run=dry_run)
        if status != "absent":
            results.append((path, status))

    generated = {
        "cursor": ".cursor/rules/voice-contract.mdc",
        "cline": ".clinerules/voice-contract.md",
        "windsurf": ".windsurf/rules/voice-contract.md",
        "aider": ".aider.voice.yml",
    }
    for target, relative in generated.items():
        if target not in selected:
            continue
        path = root / relative
        status = _remove_generated_file(path, root=root, dry_run=dry_run)
        if status != "absent":
            results.append((path, status))

    for target in selected:
        target_state.pop(target, None)
    state_result = _write_state(
        root, state, existed=state_existed, dry_run=dry_run
    )
    if state_result:
        results.append(state_result)
    return results
